### ISSUE TITLE
Improve all.development_documents.reference.md

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#687] opened 2024-02-25 23:12 UTC
We want to make sure that:
- all the docs in docs/onboarding/all.development_documents.reference.md exist
- all important docs in `docs` are referred to in that file

This doc contains pointers to all the documents related to our development.

This can be outsourced

FYI @samarth9008

**Comment by nehalR777** [comment] 2024-02-26 19:20
Hey @samarth9008 , Thanks for assigning me this task. It would be really helpful if you could help me with a short briefing on what is expected here. 
cc: @sonaalKant

**Comment by nehalR777** [comment] 2024-02-26 23:15
Hey @samarth9008 , I am almost done with updating the broken links in the document and making changes accordingly, just want to cross-check if this is the correct place [DataPull](https://github.com/sorrentum/sorrentum/blob/master/docs/datapull/all.datapull_client_stack.explanation.md) should be pointing to? 


Also could not locate relevant documents for the following in the repo : 
1) HTMLcov server mentioned [here](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/all.development_documents.reference.md#in-depth-docs)
2) Codebase Clean-up mentioned [here](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/all.development_documents.reference.md#learn-how-to-become-efficient-at-developing)

cc: @sonaalKant @gpsaggese

**Comment by gpsaggese** [comment] 2024-02-27 02:36
1) Yes, the idea is to make sure that all the md files pointed in the doc exists. We have a script to do this automatically, but it's not ready yet for prime time

2) You can remove the reference to datapull and dataflow 
```
100 - [DataFlow](/docs/dataflow/ck.dataflow.explanation.md)
101
102 - [DataPull](/docs/datapull/ck.datapull.explanation.md)
```

3) You can remove the reference to HTMLcov

4) The code clean up doesn't exist and it was probably deleted by mistake
```
> find . -name "*clean_up_codebase*"
```
and I think we should check in the Git history

**Comment by nehalR777** [comment] 2024-02-27 03:35
@gpsaggese @samarth9008, is this the right codebase clean-up file? Could you please let me know which directory this file should go into, in the repository? 

# Codebase clean-up scripts



- [Using the script approach](#using-the-script-approach)
- [Rationale for the script approach](#rationale-for-the-script-approach)
- [Notes on `replace_text.py`](#notes-on-replace_textpy)
- [Usage examples](#usage-examples)
- [Instructions for the PR author](#instructions-for-the-pr-author)
  * [Example](#example)
- [Instructions for the subrepo integrator](#instructions-for-the-subrepo-integrator)



## Using the script approach

- We want to apply clean-up changes to the code base with a script
  - Ideally we would like to apply all the changes automatically through the
    script
  - E.g.: in [SorrTask258](https://github.com/sorrentum/sorrentum/issues/258) a
    script that replaces `pytest.raises` with `self.assertRaises` everywhere in
    the code
- We are ok to make the vast majority (like 95%) of the changes automatically,
  and the rest manually
- We want to keep together in a single PR
  - the script performing automatically the changes and
  - the manual changes from the outcome of the script
- We don't want to check in the PR, the outcome of running the script
  - We can create a separate PR to communicate with the reviewers the output of
    running the script
- The reviewer should run the script on all the repos, run the unit tests, and
  merge (through a PR as usual)
- Typically we use
  [replace_text.py](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/replace_text.py)
  and wrap it up in a `sh` script
- For more complex problems we write a custom regex-based script

## Rationale for the script approach

- Since we have multiple repos, we can't always easily replace code in one repo
  (e.g., with PyCharm) and have all the other repos work properly
  - So we create a script that applies the correct changes to all the repos
- When developing a change for the entire repo, we want to be able to "reset"
  the work and apply the change from scratch
- Often during the review of the PR:
  - the code in master might be changing creating conflicts
  - the reviewers might ask some changes
  - Using the non-script approach, this creates a lot of manual changes. Instead
    with the script approach we can check out master, run the script to apply
    the changes automatically, regress and merge

## Notes on `replace_text.py`

- Replace an instance of text in all:
  - `.py` file contents
  - `.ipynb` file contents
  - `.txt` file contents
  - filenames
- `--old`: regular expression or string that should be replaced with `--new`
- `--new`: regular expression or string that should replace `--old`
- `--preview`: see script result without making actual changes
- `--only_dirs`: provide space-separated list of directories to process only
- `--only_files`: provide space-separated list of files to process only
- `--exclude_files`: provide space-separated list of files to exclude from
  replacements
- `--exclude_dirs`: provide space-separated list of dir to exclude from
  replacements
- `--ext`: process files with specified extensions
  - defaults are `py, ipynb, txt, sh`
  - use `_all_` for all files

## Usage examples

- See [SorrIssue259](https://github.com/sorrentum/sorrentum/issues/259) and the
  related [PR](https://github.com/sorrentum/sorrentum/pull/336) for reference
  - We wanted to make `_to_multiline_cmd()` from `helpers/lib_tasks_utils.py` a
    public function
  - This would require to rename `_to_multiline_cmd()` to `to_multiline_cmd()`
    with the script
  - This
    [script](https://github.com/cryptokaizen/cmamp/blob/master/dev_scripts/cleanup_scripts/SorrTask259_Make_to_multi_line_cmd_public.sh)
    will make the replacement smoothly everywhere in the code except for the
    dirs specified `--exclude_dirs` flag.

- See [SorrIssue258](https://github.com/sorrentum/sorrentum/issues/258) and the
  related [PR](https://github.com/sorrentum/sorrentum/pull/350) for reference
  - We wanted to replace `pytest.raises` with `self.assertRaises`
  - This
    [script](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/cleanup_scripts/SorrTask258_Replace_pytest_raises_with_self_assertraises.sh)
    will replace it everywhere in the code
  - Note the use of `--ext` flag to specify the file extentions the script
    should work on
- Of course the changes need to be applied in one repo and then propagated to
  all the other repos if the tests are successful

## Instructions for the PR author

- Create a local branch called `...TaskXYZ_..._script` containing:
  - The code that needs to be changed manually
    - E.g.: Replacing `pytest.raises` with `self.assertRaises`
  - More contextual changes
    - E.g.: Adding unit tests to the new functions
  - The script for the replacement of the caller named after the GH issue
    - The script should:
      - Prepare the target Git client
      - Merge this `script` branch with the manual changes
      - Make the automated changes
        - E.g.: Rename a function or replace certain word in comments /
          docstring
  - Notes in the files that need to be changed manually after the automatic
    script
- Run from scratch the script getting the regression to pass
  - Any time there is a change needed by hand, the change should be added to the
    script branch
  - The goal is to be able to run the script
- File a PR of the `...TaskXYZ_..._script`
- (Optional) Create a PR with the result of the script
  - The author can request a review on this PR, but still the goal is to
    automate as much as possible
- Finally the PR author merges the PR with the results of the script

### Example

- The name of script should be related to the task. E.g:
  `SorrTask259_Make_to_multi_line_cmd_public.sh`
- The script should have a system call to `replace_text.py` to execute the
  required functionality as provided in the above examples
- Create a PR only with the script and the changes

## Instructions for the subrepo integrator

- Do a `git checkout` of the `...TaskXYZ_..._script`
- Run the script
- Review carefully the changes to make sure we are not screwing things up
- Run the regressions
- Merge the resulting `...TaskXYZ...` PR
- Ensure that the `...TaskXYZ_..._script` is merged in `master`
- Delete the `...TaskXYZ_..._script`

**Comment by samarth9008** [comment] 2024-02-27 13:36
Here is the link with the codebase clean-up doc 
https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.replace_text.how_to_guide.md

Lets change its name to `all.codebase_clean_up.how_to_guide.md` and update it accordingly

**Comment by nehalR777** [comment] 2024-02-27 16:16
@samarth9008 @gpsaggese , this has been fixed and a PR has been created.

**Comment by gpsaggese** [comment] 2024-02-28 01:29
FYI we try to use links as much as possible
- E.g., instead of copy-paste in https://github.com/sorrentum/sorrentum/issues/687#issuecomment-1965727399 you could have used the path to the file in an old GitHub commit
- E.g., here you can use the PR link to simplify people's lives. PR is filed, but where it is?

Also no need to always specify who you are talking to. Once we are tagged in an issue we get notified all the time and in general, we read all the bugs all the time.

**Comment by nehalR777** [comment] 2024-02-28 02:44
The PR for this issue has been created here https://github.com/sorrentum/sorrentum/pull/698

**Comment by nehalR777** [comment] 2024-02-28 18:45
This has been resolved and the PR https://github.com/sorrentum/sorrentum/pull/698 has been merged to the master branch.

**Closed by nehalR777** 2024-02-28 18:45 UTC
Labels: Outsource
