### ISSUE TITLE
Error while running linter

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#277] opened 2023-05-23 14:21 UTC
Tried setting up linter with `source dev_scripts/client_setup/build.sh` and `source dev_scripts/setenv_amp.sh`. However faced erros.

![image](https://github.com/sorrentum/sorrentum/assets/58821247/1938cbe9-6abe-4d0c-a171-4dc7a1f1646b)
![2](https://github.com/sorrentum/sorrentum/assets/58821247/ef889060-8bb7-431d-89ee-e342d879edd9)
![3](https://github.com/sorrentum/sorrentum/assets/58821247/e2c8c26b-5768-4248-9857-608552fa0fbc)

Also tried executing `i docker_pull` and `i git_merge_master` which executed successfully.

While running `i docker_login` it gave me this error.
![image](https://github.com/sorrentum/sorrentum/assets/58821247/b3ba45f6-6357-4746-91b3-afe0c1af0f59)

One noteable warning from running the `i lint --files .....` was `invalid host`, can be seen in the first screenshot.

**Comment by gpsaggese** [comment] 2023-05-23 14:43
We have two flows: one for Sorrentum and one for `cmamp` / Kaizen. With cmamp you access all our infra.
@jsmerix will on-board you on `cmamp`

`i docker_login` I think you need an AWS key to get the Docker container.
@jsmerix how do we fetch the container from Docker Hub?

In any case, we should make sure both flows work.

@PomazkinG this seems an old problem that was fixed and maybe I've messed up during the integration :-(
Can you pls double check?

**Comment by PomazkinG** [comment] 2023-05-23 20:34
@samarth9008 thx for reporting, let's try to figure out together 

1) Next time could you please copy-paste the error from the cmd line? Typically to debug we need to copy-paste certain text (e.g., to grep), with screenshots it is impossible. I would appreciate if you enforce this invariant within the team, it's the common problem. Maybe you could even add a few lines about that in https://github.com/sorrentum/sorrentum/blob/master/docs/GitHub_ZenHub_workflows.md#issue-workflows
2) Interesting that you receive an error because it should just issues a warning (see [here](https://github.com/sorrentum/sorrentum/blob/master/helpers/hserver.py#L235)). Do you have the latest master?
3) For the context: we have a list of "approved" computers that we work on and the failing piece of code checks that your machine belongs to that list of "approved" machines. This works well on the CK side because we all use the remote servers while on the Sorrentum side it does not work because you guys work on your personal PCs. However, it should not be a problem if the check issues a warning instead of raising an error.
4) `i docker_login` should not be a problem because you don't need, we use it to access the private Docker registries while you guys are working with the publicly available copies of our Docker images (if I understood correctly).

**Comment by samarth9008** [comment] 2023-05-24 13:42
> 2. Interesting that you receive an error because it should just issue a warning (see [here](https://github.com/sorrentum/sorrentum/blob/master/helpers/hserver.py#L235)). Do you have the latest master?
Yeah I updated the master before running the linter.


Here is log of the error.

```
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/home/sorrentum/src/venv/amp.client_venv/bin/invoke lint --files defi/tulip/test/test_dao_cross_sol.py'
report_memory_usage=False report_cpu_usage=False
## lint: 
09:40:42 - INFO  lib_tasks_lint.py lint:378                             Files to lint:
defi/tulip/test/test_dao_cross_sol.py
09:40:42 - WARN  <string> _raise_invalid_host:90                        Don't recognize host: host_os_name=Linux, am_host_os_name=None
(IMAGE=sorrentum/dev_tools:prod \
        docker-compose \
        --file /home/sorrentum/src/sorrentum1/devops/compose/docker-compose.yml \
        --env-file devops/env/default.env \
        run \
        --rm \
        --name sorrentum.cmamp.linter.sorrentum1.20230524_094042 \
        --user $(id -u):$(id -g) \
        linter \
        pre-commit run -c /app/.pre-commit-config.yaml --files defi/tulip/test/test_dao_cross_sol.py ) 2>&1 | tee -a linter_output.txt
The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The AM_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The AM_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The AM_FORCE_TEST_FAIL variable is not set. Defaulting to a blank string.
The AM_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
The CK_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The CK_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The CK_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The CK_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
Creating compose_linter_run ... 
Creating compose_linter_run ... done
##> devops/docker_run/entrypoint.sh
UID=1000
GID=1000
# Activate environment
##> /app/devops/docker_run/setenv.sh
# Set PATH
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Set PYTHONPATH
PYTHONPATH=/app:/app/amp:
# Configure env
git --version: git version 2.25.1
/src
WARNING: AWS credential check failed: can't find /home/.aws/credentials file.
WARNING: AWS credential check failed: can't find /home/.aws/config file.
# Check AWS authentication setup

The config profile (am) could not be found
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                       am           manual    --profile
AM_CONTAINER_VERSION='1.2.0'
which python: /venv/bin/python
python -V: Python 3.8.10
pandas: 1.4.4
helpers: <module 'helpers' from '/src/helpers/__init__.py'>
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/app:/app/amp:
entrypoint.sh: 'pre-commit run -c /app/.pre-commit-config.yaml --files defi/tulip/test/test_dao_cross_sol.py'
Traceback (most recent call last):
  File "/venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/venv/lib/python3.8/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/tasks.py", line 10, in <module>
    from helpers.lib_tasks import (  # This is not an invoke target.
  File "/app/amp/helpers/lib_tasks.py", line 14, in <module>
    from helpers.lib_tasks_docker import *  # isort:skip  # noqa: F401,F403 # pylint: disable=unused-import,unused-wildcard-import,wildcard-import
  File "/app/amp/helpers/lib_tasks_docker.py", line 21, in <module>
    import helpers.henv as henv
  File "/app/amp/helpers/henv.py", line 16, in <module>
    import helpers.hversion as hversio
  File "/app/amp/helpers/hversion.py", line 23, in <module>
    import helpers.hserver as hserver
  File "/app/amp/helpers/hserver.py", line 212, in <module>
    _dassert_setup_consistency()
  File "/app/amp/helpers/hserver.py", line 203, in _dassert_setup_consistency
    raise ValueError(msg)
ValueError: One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
1
09:40:54 - INFO  lib_tasks_lint.py lint:408                             Parsing 'linter_output.txt'
09:40:54 - INFO  lib_tasks_lint.py lint:413                             Saved cfile in './linter_warnings.txt'
```

Although I have the server access now and it works successfully.

**Comment by PomazkinG** [comment] 2023-05-24 20:40
I see now what is happening.

The linter is run using the `dev_tools` image. In the `dev_tools` repo the submodule is `cmamp`, not `sorrentum` that is why it raises instead of issuing a warning

seems like we need to:
- `raise ValueError(msg)` -> `_LOG.warn(msg)` in `_dassert_setup_consistency()` in `helpers/hserver.py` in `cmamp`
- update the `dev_tools` repo
- release the `dev_tools` image to the CK
- copy again to the public registry

@gpsaggese did I understand the problem correctly or there is a simpler way to fix this?

**Comment by DanilYachmenev** [comment] 2023-05-26 11:07
> @gpsaggese did I understand the problem correctly or there is a simpler way to fix this?

@gpsaggese pinging you on this one again since it seems kind of blocking - other students cannot run linter because of that
#167, for example

and my knowledge of linter and `dev_tools` in general is quite limited to confirm Grisha's thoughts
so yeah, wdyt?

**Comment by gpsaggese** [comment] 2023-05-26 11:59
Very good insight @PomazkinG. I think the issue is that we release the dev_tools with cmamp copied inside, so the fix applied to Sorrentum is not picked up. 

Your solution makes sense. For simplicity I would apply the same fix from Sorrentum to cmamp (since we will need to allow people to run cmamp on their laptop), and then release as you suggested.

**Comment by PomazkinG** [comment] 2023-05-26 13:40
The fix is applied to `cmamp`. 

However, I cannot easily release the `dev_tools` image.

```
> i docker_release_dev_image --version 1.2.1 --no-update-poetry
...
# Install jupyter extensions                                                                                                                                                                              
++ '[' 'x(venv) ' '!=' x ']'                                                                                                                                                                              
++ PS1='(venv) '                                                                                                                                                                                          
++ export PS1                                                                                                                                                                                             
++ '[' -n /usr/bin/bash -o -n '' ']'                                                                                                                                                                      
++ hash -r                                                                                                                                                                                                
+ echo '# Install jupyter extensions'                                                                                                                                                                     
++ jupyter --data-dir                                                                                                                                                                                     
Jupyter data dir: /home/.local/share/jupyter                                                                                                                                                              
+ DIR_NAME=/home/.local/share/jupyter                                                                                                                                                                     
+ echo 'Jupyter data dir: /home/.local/share/jupyter'                                                                                                                                                     
+ [[ ! -d /home/.local/share/jupyter ]]                                                                                                                                                                   
+ mkdir -p /home/.local/share/jupyter                                                                                                                                                                     
+ jupyter contrib nbextension install                                                                                                                                                                     
Error executing Jupyter command 'contrib': [Errno 2] No such file or directory                                                                                                                            
The command '/bin/sh -c /bin/sh -c "./install_jupyter_extensions.sh"' returned a non-zero code: 1                                                                                                         
Command exited with non-zero status 1     
```

Probably it has something to do with the Jupyter version being updated. Will take a closer look on Mon.

**Comment by gpsaggese** [comment] 2023-05-26 13:48
I've googled the error and it seems to be an old one... https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1348

The fix seems to rename the exec (note the dash)
```
> jupyter-contrib nbextension install
```

Man, Jupyter is so unstable.

**Comment by PomazkinG** [comment] 2023-05-26 15:37
> The fix seems to rename the exec (note the dash)

> jupyter-contrib nbextension install

no luck:
```
+ jupyter-contrib nbextension install
./install_jupyter_extensions.sh: /venv/bin/jupyter-contrib: /home/josh/miniconda3/envs/jup/bin/python: bad interpreter: No such file or directory
```

now people say that the dash is the problem, will try to debug

**Comment by PomazkinG** [comment] 2023-05-29 19:33
ok seems like the solution was to `jupyter contrib nbextension install` -> `jupyter contrib-nbextension install`, the same dash thing but in the different place.

I was able to release the dev image, but when trying to release the prod image I receive:
```
> i docker_login
Login Succeeded
> i docker_release_prod_image --no-push-to-repo --version 1.2.1
Sending build context to Docker daemon  601.2MB
Step 1/3 : ARG VERSION
Step 2/3 : FROM ******.dkr.ecr.us-east-1.amazonaws.com/dev_tools:dev-${VERSION}
pull access denied for ********.dkr.ecr.us-east-1.amazonaws.com/dev_tools, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.
Command exited with non-zero status 1
```

@jsmerix can you please help? Trying to build the `dev_tools` prod image using the [prod Dockerfile](https://github.com/alphamatic/dev_tools/blob/master/devops/docker_build/prod.Dockerfile) but it says I need to login while I have logged in before running the cmd

**Comment by PomazkinG** [comment] 2023-05-29 19:39
@jsmerix nvm, for some reason it was `us-east-1` instead of `eu-north-1` in the base image name

**Comment by PomazkinG** [comment] 2023-05-29 19:51
the prod image is out in our private Docker registry

```
REPOSITORY                                                TAG                     IMAGE ID       CREATED             SIZE                                                                                 
****dkr.ecr.eu-north-1.amazonaws.com/dev_tools   prod                    506992289894   3 minutes ago       3.94GB                                                                               
****.dkr.ecr.eu-north-1.amazonaws.com/dev_tools   prod-1.2.1              506992289894   3 minutes ago       3.94GB   
```

@jsmerix could you please transfer the image from the private Docker registry to the public one? so that the guys can use it on the Sorrentum side

**Comment by jsmerix** [comment] 2023-05-29 20:41
To clarify since there has been a misunderstanding:
`...dkr.ecr.eu-north-1.amazonaws.com...` is our private repository hosted by AWS, accessible only via API keys

Sorrentum images are hosted by `hub.docker.com` (`docker.io`). This is a separate public repository, An image has to be manually transferred from private to public repo in order to be visible publicly, i.e. pull from private, retag locally and push to public.

I have updated `sorrentum/dev_tools:prod` to match our private image.

**Comment by PomazkinG** [comment] 2023-05-29 20:49
thx Juraj!

@samarth9008 can you please run `docker pull sorrentum/dev_tools:prod` and then `i lint -f helpers/hserver.py` from your local PC and check if it works?

**Comment by samarth9008** [comment] 2023-05-29 21:12
I am facing a different error now.

```
report_memory_usage=False report_cpu_usage=False
## lint: 
rm linter_output.txt
17:10:38 - INFO  lib_tasks_lint.py lint:378                             Files to lint:
helpers/hserver.py
17:10:38 - WARN  <string> _raise_invalid_host:90                        Don't recognize host: host_os_name=Linux, am_host_os_name=None
(IMAGE=sorrentum/dev_tools:prod \
        docker-compose \
        --file /home/sorrentum/src/sorrentum1/devops/compose/docker-compose.yml \
        --env-file devops/env/default.env \
        run \
        --rm \
        --name sorrentum.cmamp.linter.sorrentum1.20230529_171038 \
        --user $(id -u):$(id -g) \
        linter \
        pre-commit run -c /app/.pre-commit-config.yaml --files helpers/hserver.py ) 2>&1 | tee -a linter_output.txt
The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The AM_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The AM_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The AM_FORCE_TEST_FAIL variable is not set. Defaulting to a blank string.
The AM_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
The CK_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The CK_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The CK_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The CK_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
Creating compose_linter_run ... 
Creating compose_linter_run ... done
##> devops/docker_run/entrypoint.sh
UID=1000
GID=1000
# Activate environment
##> /app/devops/docker_run/setenv.sh
# Set PATH
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Set PYTHONPATH
PYTHONPATH=/app:/app/amp:
# Configure env
git --version: git version 2.25.1
/src
WARNING: AWS credential check failed: can't find /home/.aws/credentials file.
WARNING: AWS credential check failed: can't find /home/.aws/config file.
# Check AWS authentication setup
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                       am           manual    --profile

The config profile (am) could not be found
AM_CONTAINER_VERSION='1.2.0'
which python: /venv/bin/python
python -V: Python 3.8.10
pandas: 1.4.3
helpers: <module 'helpers' from '/src/helpers/__init__.py'>
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/app:/app/amp:
entrypoint.sh: 'pre-commit run -c /app/.pre-commit-config.yaml --files helpers/hserver.py'
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/venv/bin/invoke print_env'
report_memory_usage=False report_cpu_usage=False
17:10:49 - WARN  henv.py get_repo_config_file:485                       Using value '/app/repo_config.py' for AM_REPO_CONFIG_PATH from env var
Traceback (most recent call last):
  File "/venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/venv/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/venv/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/venv/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/app/amp/helpers/lib_tasks_print.py", line 85, in print_env
    print(henv.env_to_str())
  File "/app/amp/helpers/henv.py", line 217, in env_to_str
    msg += hprint.indent(execute_repo_config_code("config_func_to_str()"))
  File "/app/amp/helpers/henv.py", line 519, in execute_repo_config_code
    ret = eval(code_to_execute)
  File "<string>", line 1, in <module>
  File "<string>", line 433, in config_func_to_str
  File "<string>", line 1, in <module>
  File "<string>", line 274, in get_shared_data_dirs
  File "<string>", line 145, in _raise_invalid_host
ValueError: Don't recognize host: host_os_name=Linux, am_host_os_name=Linux
1
17:10:50 - INFO  lib_tasks_lint.py lint:408                             Parsing 'linter_output.txt'
17:10:50 - INFO  lib_tasks_lint.py lint:413                             Saved cfile in './linter_warnings.txt'
```

**Comment by PomazkinG** [comment] 2023-05-29 21:14
> I am facing a different error now.

Good sign :) Will fix the rest also

**Comment by gpsaggese** [comment] 2023-05-29 23:30
@jsmerix should we file a bug to consolidate all the repos under GitHub (IIRC this would save us money from AWS in network traffic and avoid redundancy in maintaining the container repo)? Not super important, but worth doing if it simplifies our life

**Comment by jsmerix** [comment] 2023-05-30 10:11
> @jsmerix should we file a bug to consolidate all the repos under GitHub (IIRC this would save us money from AWS in network traffic and avoid redundancy in maintaining the container repo)? Not super important, but worth doing if it simplifies our life

To completely move away from ECR is not a completely trivial task (update codebase, update pointers in ECS task + set-up authentication, test in preprod, do a prod release)
- There would be some savings but nothing super significant
- The problem is this can't be done as a background task because of the process described above and I am not sure this is on critical path at the moment.
- If we feel like problems related to this are piling up then we can take action.

**Comment by PomazkinG** [comment] 2023-05-30 17:50
@jsmerix could you please repeat the operation from https://github.com/sorrentum/sorrentum/issues/277#issuecomment-1567464474? I've updated the image one more time since it solved one problem but another one appeared

```
REPOSITORY                                                TAG       IMAGE ID       CREATED          SIZE                                                                                                  
******.dkr.ecr.eu-north-1.amazonaws.com/dev_tools   prod      d54af9f325e8   14 seconds ago   3.97GB   
```

**Comment by jsmerix** [comment] 2023-05-30 18:03
Done.

In any case, @samarth9008 has access to the private repo so he can test any flow that is needed here without needing to repush after every adjustment.
`i docker_pull_dev_tools -s prod` in cmamp environment and then
`docker tag 623860924167.dkr.ecr.eu-north-1.amazonaws.com/dev_tools:prod sorrentum/dev_tools:prod`

**Comment by PomazkinG** [comment] 2023-05-30 18:41
> In any case, @samarth9008 has access to the private repo

@samarth9008 so you can access cmamp from your local PC? or just from one of the dev servers?

could you please repeat the steps from https://github.com/sorrentum/sorrentum/issues/277#issuecomment-1567502944? Hopefully the error will go away

**Comment by samarth9008** [comment] 2023-05-30 20:57
I pulled the new image but the error is still the same.

**Comment by PomazkinG** [comment] 2023-05-30 21:54
> I pulled the new image but the error is still the same.

weird, I'll try to set-up everything locally and test

**Comment by PomazkinG** [comment] 2023-05-31 19:25
well, the linter works locally for me. but that is probably I am using Mac which is on the list of known hosts

> Using value '/app/repo_config.py' for AM_REPO_CONFIG_PATH from env var

Probably I have to also fix the `repo_config.py` in the `dev_tools` repo, not only in `cmamp`

**Comment by PomazkinG** [comment] 2023-05-31 19:58
@samarth9008 I have updated the image, can you please test as in https://github.com/sorrentum/sorrentum/issues/277#issuecomment-1568853431?

I assume that you do everything from a local PC.
1) from cmamp: pull the image `623860924167.dkr.ecr.eu-north-1.amazonaws.com/dev_tools:prod`
2) from cmamp: tag it as `sorrentum/dev_tools:prod`
3) from sorrentum: try to run the linter

if you cannot pull `623860924167.dkr.ecr.eu-north-1.amazonaws.com/dev_tools:prod` from your local PC feel free to ask @jsmerix to push the image to the Docker hub

**Comment by jsmerix** [comment] 2023-05-31 20:25
@samarth9008 Pulling from local PC won't work because of permissions so I updated the `sorrentum/dev_tools:prod`
Ideally though it would be good to try to make sorrentum env happen on dev server if problems persists to avoid this back and forth.

**Comment by PomazkinG** [comment] 2023-05-31 20:27
@samarth9008 then it's just https://github.com/sorrentum/sorrentum/issues/277#issuecomment-1567502944 to test the linter

**Comment by samarth9008** [comment] 2023-05-31 20:57
It works successfully. Thank you so much!!!!

**Comment by PomazkinG** [comment] 2023-06-01 14:17
@samarth9008 last thing: could you please file a PR in `cmamp`?

update [here](https://github.com/cryptokaizen/cmamp/blob/master/devops/docker_build/install_jupyter_extensions.sh#L26) using the code below
```
# Install extensions. For some reason it requires a dash between `contrib`
# and `nbextension` even though it is not mentioned in the official docs.
# https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html#install-javascript-and-css-files.
jupyter contrib-nbextension install
```

**Comment by PomazkinG** [comment] 2023-06-01 15:58
finally done, closing

**Closed by PomazkinG** 2023-06-01 15:58 UTC
