### ISSUE TITLE
`invoke` tasks doesn't work from sorrentum

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#370] opened 2023-06-30 13:55 UTC
None of the invoke tasks works from the sorrentum side after pulling the latest master.

Error:
```
(amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ i docker_bash
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/home/sorrentum/src/venv/amp.client_venv/bin/invoke docker_bash'
## docker_bash: 
Traceback (most recent call last):
  File "/home/sorrentum/src/venv/amp.client_venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/home/sorrentum/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/home/sorrentum/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/home/sorrentum/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/sorrentum/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 1275, in docker_bash
    docker_cmd_ = _get_docker_compose_cmd(
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 1121, in _get_docker_compose_cmd
    docker_cmd_ = _get_docker_base_cmd(
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 1036, in _get_docker_base_cmd
    image = get_image(base_image, stage, version)
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 930, in get_image
    base_image = _get_base_image(base_image)
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 887, in _get_base_image
    _dassert_is_base_image_name_valid(base_image)
  File "/home/sorrentum/src/sorrentum1/helpers/lib_tasks_docker.py", line 873, in _dassert_is_base_image_name_valid
    hdbg.dassert(m, "Invalid base_image: '%s'", base_image)
  File "/home/sorrentum/src/sorrentum1/helpers/hdbg.py", line 159, in dassert
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/home/sorrentum/src/sorrentum1/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/home/sorrentum/src/sorrentum1/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
cond=None
Invalid base_image: 'sorrentum/cmamp'
################################################################################

```

FYI @DanilYachmenev

**Comment by gpsaggese** [comment] 2023-06-30 15:23
1) Good job debugging and proposing solutions
2) The root cause is that we have a bit of bandaids for sorrentum vs cmamp, while we should think a little more of how things should work at high level
3) We don't have unit test coverage for this repo so I didn't catch this issue :-(

As to the solution, just looking at the code quickly IMO we should allow a valid image to have both a IP address (like in `_INTERNET_ADDRESS_RE`) or be a local path like `sorrentum`.

This fix should also fix the other bandaid 
```
    # TODO(Grisha): difference between `cmamp` and `sorrentum`.
    # TODO(Grisha): add suport for names like `sorrentum/cmamp`.
    if False:
```

The problem is that the regex now it's a regex-from-hell

I would convert it in something that can be understood by humans like:
```
def is_valid_base_image(...):
        # E.g., *****.dkr.ecr.us-east-1.amazonaws.com/amp   
        regex = rf"^{_INTERNET_ADDRESS_RE}\/{_IMAGE_BASE_NAME_RE}$"
         _LOG.debug("Testing with regex='%s'", regex)
        m = re.match(regex, image)
        hdbg.dassert(m, "Invalid image: '%s'", image)    
        if m:
            return True
        # :local-saggese        
        regex = rf":{_IMAGE_STAGE_RE}$",

...
                # -1.0.0
                rf"(-{_IMAGE_VERSION_RE})?$",
            ]
        )
```

Then I would unit test `_is_valid_base_image` with all the possible image so we also document everything that is legal and illegal. Not sure "who is in charge" of that regex, @jsmerix or @PomazkinG ?

**Comment by gpsaggese** [comment] 2023-06-30 15:29
BTW since this is a break that will create problem with the interns it's ok to make a quick PR to "fix" the code as it was before (if you know how to solve the problem) while we do the fix properly.

In an ideal world my change should have not passed the checks and be committed. As Linux says: "we never, ever break the build".

**Comment by jsmerix** [comment] 2023-06-30 15:35
> The problem is that the regex now it's a regex-from-hell

I'd say to give-up the compactness of single regex in favour of readability/maintainability and just do two regexes and wrap the checking into a separate function.

**Comment by gpsaggese** [comment] 2023-06-30 15:36
Yes, exactly my proposal. The regex is write-only now.

**Comment by samarth9008** [comment] 2023-07-19 14:27
@hhxjqm Temporary solution is already implemented. You need to improve the RE to make it work and remove the `if False:` from the function.

**Closed** 2023-07-24 23:31 UTC
