### ISSUE TITLE
Unit test `plot_slippage_boxplot()` 

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#459] opened 2023-07-26 13:43 UTC
We need to unit test `plot_slippage_boxplot()` from [core/plotting/slippage.py](https://github.com/sorrentum/sorrentum/blob/8f557a920251a972b1f6e3190141f03eee226048/core/plotting/slippage.py#L16)

Create a simple test DF for the test.

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by samarth9008** [comment] 2023-08-08 19:05
As @christyanthony is taking time off, re-routing it to @asawhn0128

**Comment by why2000** [comment] 2023-09-18 22:41
For double-checking: The method to be tested [core/plotting/slippage.py](https://github.com/sorrentum/sorrentum/blob/8f557a920251a972b1f6e3190141f03eee226048/core/plotting/slippage.py#L16) is no longer on master, but on an already merged branch #359 , is that expected?

**Comment by DanilYachmenev** [comment] 2023-09-19 11:27
> @samarth9008 @DanilYachmenev For double-checking: The method to be tested [core/plotting/slippage.py](https://github.com/sorrentum/sorrentum/blob/8f557a920251a972b1f6e3190141f03eee226048/core/plotting/slippage.py#L16) is no longer on master, but on an already merged branch #359 , is that expected?

Oh, the function has actually been moved and renamed while the issue was open
Now it is `plot_boxplot()` at `core/plotting/boxplot.py`
So yeah, apart from it the task is the same

**Comment by why2000** [comment] 2023-09-19 17:58
@DanilYachmenev @samarth9008 The unit test for that method is failing ONLY when running multiple unit tests together, due to a bug that I think comes from pandas boxplot. I tried to figure the cause and have a summary of how the bug can be reproduced:
Given any two dataframes, the first `df1` has more rows than cols, the second `df2` has more cols than rows, run pandas df's boxplot() method on df1, then on df2, will cause a inner bug in pandas.
```python
data1 = {
            "Column1": np.random.rand(5),
            "Column2": np.random.rand(5),
            "Column3": np.random.rand(5),
            "Column4": np.random.rand(5),
        }
df1 = pd.DataFrame(data1)
data2 = {
            "Column"+str(i): np.random.rand(4) for i in range(1, 6)
        }
df2 = pd.DataFrame(data2)
df1.boxplot(rot=45, ylabel="")
df2.boxplot(rot=45, ylabel="")
``` 
The above code would cause an Assertion failure inside pandas code here [boxplot.py](https://github.com/pandas-dev/pandas/blob/2.1.x/pandas/plotting/_matplotlib/boxplot.py#L389)
With the following error message:
```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[89], line 13
     11 df2 = pd.DataFrame(data2)
     12 df1.boxplot(rot=45, ylabel="")
---> 13 df2.boxplot(rot=45, ylabel="")

File /venv/lib/python3.8/site-packages/pandas/plotting/_core.py:516, in boxplot_frame(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, backend, **kwargs)
    499 @Substitution(backend=_backend_doc)
    500 @Appender(_boxplot_doc)
    501 def boxplot_frame(
   (...)
    513     **kwargs,
    514 ):
    515     plot_backend = _get_plot_backend(backend)
--> 516     return plot_backend.boxplot_frame(
    517         self,
    518         column=column,
    519         by=by,
    520         ax=ax,
    521         fontsize=fontsize,
    522         rot=rot,
    523         grid=grid,
    524         figsize=figsize,
    525         layout=layout,
    526         return_type=return_type,
    527         **kwargs,
    528     )

File /venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py:458, in boxplot_frame(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
    443 def boxplot_frame(
    444     self,
    445     column=None,
   (...)
    454     **kwds,
    455 ):
    456     import matplotlib.pyplot as plt
--> 458     ax = boxplot(
    459         self,
    460         column=column,
    461         by=by,
    462         ax=ax,
    463         fontsize=fontsize,
    464         grid=grid,
    465         rot=rot,
    466         figsize=figsize,
    467         layout=layout,
    468         return_type=return_type,
    469         **kwds,
    470     )
    471     plt.draw_if_interactive()
    472     return ax

File /venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py:437, in boxplot(data, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
    434     else:
    435         data = data[columns]
--> 437     result = plot_group(columns, data.values.T, ax, **kwds)
    438     ax.grid(grid)
    440 return result

File /venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py:376, in boxplot.<locals>.plot_group(keys, values, ax, **kwds)
    374 if len(ticks) != len(keys):
    375     i, remainder = divmod(len(ticks), len(keys))
--> 376     assert remainder == 0, remainder
    377     keys *= i
    378 if is_vertical:

AssertionError: 4

```

**Comment by DanilYachmenev** [comment] 2023-09-19 18:52
@why2000 nice debugging, good approach to provide reproducible case

I suppose the reason behind it might be in figure/axis inheritance

However, let's not be too specific here and add 2 simple unit tests
I'll be more specific in the PR
But yeah, lets not spend too much time here since this one is not crucial - just make tests pass and expamples be displayed in the notebook

**Closed** 2023-09-25 10:32 UTC
Labels: Outsource

**Comment by gpsaggese** [comment] 2023-09-25 12:12
@DanilYachmenev can you do a quick PR to `cmamp` to merge the changes from `Sorrentum`. No review IMO, it can go straight in
