### ISSUE TITLE
Switch everyone to the Docker Jupyter container

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#45] opened 2023-03-04 21:02 UTC
To make simpler to collaborate we want to have everyone use the official Docker Jupyter container.
The beauty is that everyone has exactly the same set-up so that it's easy to collaborate instead of wasting a large amount of time in "it works for me", "it doesn't work for you"

Instructions for the container is:
https://github.com/sorrentum/sorrentum/blob/master/sorrentum_sandbox/altdata_examples/tutorial_jupyter.md

Also learning how to use Docker is key to working in the real world.

Slides and tutorials are in the UMD DATA605 class
https://github.com/gpsaggese/umd_data605/blob/main/lectures/02.2%20-%20Docker%20DevOps.pdf

@samarth9008 is the TA of that class so he can help with Docker questions (but not on how to install it on your laptop, that's your problem. He can help if he wants, but he is not his job to provide IT services for your laptop).

Once you are done with the switch pls mark this as done
- [x] @FirstSingularity 
- [x] @okritvik 
- [ ] @vinay06vinay 
- [x] @Chandramani05

**Comment by Chandramani05** [comment] 2023-03-04 22:49
I am getting an error ‘No such container airflow_cont’ when running doctor_bash.sh
![camphoto_1804928587](https://user-images.githubusercontent.com/32766172/222932109-c5d2263d-39cc-4148-9b3f-b7ed658b0ee1.jpeg)

**Comment by Chandramani05** [comment] 2023-03-04 22:56
Getting the same error even after pulling 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/32766172/222932328-8a336819-b701-4ced-8c14-fa8b95546da6.png">

**Comment by gpsaggese** [comment] 2023-03-04 23:17
I think you are in the wrong dir, since it works for me in the right dir (I'll improve the instructions https://github.com/sorrentum/sorrentum/blob/master/sorrentum_sandbox/altdata_examples/README.md)

```
> pwd
/Users/saggese/src/sorrentum1/sorrentum_sandbox/altdata_examples

saggese@wireless-10-104-222-208.umd.edu branch:'master' ~/src/sorrentum1/sorrentum_sandbox/altdata_examples
> docker_jupyter.sh
++ git rev-parse --show-toplevel
+ GIT_ROOT=/Users/saggese/src/sorrentum1
+ REPO_NAME=sorrentum
+ IMAGE_NAME=jupyter
+ FULL_IMAGE_NAME=sorrentum/jupyter
+ docker image ls sorrentum/jupyter
REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
sorrentum/jupyter   latest    29eea5978db1   11 days ago   1e+03MB
+ CONTAINER_NAME=jupyter
+ docker run --rm -ti --name jupyter -p 8888:8888 -v /Users/saggese/src/sorrentum1:/data sorrentum/jupyter /bin/bash -c 'source /data/sorrentum_sandbox/altdata_examples/set_env.sh; /data/sorrentum_sandbox/altdata_examples/run_jupyter.sh'
PYTHONPATH=:/data
<module 'helpers.hdbg' from '/data/helpers/hdbg.py'>
+ jupyter-notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --NotebookApp.password=
[I 23:15:02.672 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 23:15:02.678 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 23:15:05.431 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 23:15:05.596 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[I 23:15:05.663 NotebookApp] Serving notebooks from local directory: /data
[I 23:15:05.663 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 23:15:05.664 NotebookApp] http://7508b0b8a12d:8888/
[I 23:15:05.664 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

**Comment by Chandramani05** [comment] 2023-03-04 23:35
I was able to run jupyter from alt_example directory using run_jupyter.sh

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/32766172/222933502-041a8980-e5ba-4c6e-8ef9-7151c98a19c8.png">

**Comment by FirstSingularity** [comment] 2023-03-05 02:57
I was also able to run the same notebook. Will there a separate container for each project? I was only able to see that directory's files through jupyter.

**Comment by gpsaggese** [comment] 2023-03-05 03:10
We could do one container per project, but too many containers are a pain to maintain.
For now let's have one container with all the dev packages for all the projects.

One problem is that Docker is mounting the dir under `altdata_examples` and so you don't see `projects`. I'll fix it tomorrow

**Comment by okritvik** [comment] 2023-03-10 05:52
I was also able to run run_jupyter.sh from sorrentum_sandbox/examples. @Chandramani05 @FirstSingularity were you able to open jupyter from the URL given by docker_jupyter.sh?

**Comment by FirstSingularity** [comment] 2023-03-10 17:27
@okritvik I don't think that one worked, but the one on docker desktop worked for me just fine.

**Comment by samarth9008** [comment] 2023-05-25 19:53
I am not sure if it would work on windows. @gpsaggese Can you merge the #280 so that we start pointing windows people to different solution.

**Comment by samarth9008** [comment] 2023-05-25 19:59
@thejameszhang You can use [instructions](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md) on this page for windows OS.

**Comment by thejameszhang** [comment] 2023-05-25 22:20
Thanks @samarth9008 . Installed the virtual machine, so I was able to run the first two scripts, but now running into another issue. 

![image](https://github.com/sorrentum/sorrentum/assets/70459407/bdf9b924-0352-4f34-97a0-614c8f266c72)

I don't have permission to pull the latest cmamp image?

**Comment by samarth9008** [comment] 2023-05-25 22:22
Can you show the exact error you are facing?

**Comment by samarth9008** [comment] 2023-05-25 22:24
Ohh for this you have two options, since docker run as root user, either
add docker user to your user group. You can get the command by Google
search or run this command as a root user.

**Comment by gpsaggese** [comment] 2023-05-25 22:35
Yes after we fix this we need to add instructions on how to configure Ubuntu to run Docker (e.g., groups, Docker-in-Docker). @jsmerix is an expert on this too.

**Comment by gpsaggese** [comment] 2023-05-25 22:43
Also @samarth9008 this thread would also go in the one-by-one on-boarding thread.
Let's merge the instructions to the on-boarding checklist and close this one.

**Comment by thejameszhang** [comment] 2023-05-26 01:57
I was able to pull the latest cmamp image using the command `sudo docker pull sorrentum/cmamp:latest`, but now I can't merge into master or start the container. 

![image](https://github.com/sorrentum/sorrentum/assets/70459407/ab29f3be-46a0-488f-b56a-b01dba2dca83)

Error is that `s3fs` is not defined. I tried `i git_merge_master`, the `i` command is not found. Then tried using `invoke` which led to the NameError.

**Comment by thejameszhang** [comment] 2023-05-26 03:04
Update: I pip installed s3fs but still says the "One and only one set-up config should be true" and then this time a KeyError: `CK_ECR_BASE_PATH`

**Comment by gpsaggese** [comment] 2023-05-26 12:04
This is the same problem as https://github.com/sorrentum/sorrentum/issues/277

The overarching issue is that we are trying to run `cmamp` outside of our server and so we are hitting all new problems.

@PomazkinG can you try to run `cmamp` on your laptop and see what needs to be fixed?
Happy to help.

**Comment by samarth9008** [comment] 2023-05-26 13:51
> Also @samarth9008 this thread would also go in the one-by-one on-boarding thread. Let's merge the instructions to the on-boarding checklist and close this one.

I think it is already there in the checklist.

**Comment by thejameszhang** [comment] 2023-05-26 17:07
![image](https://github.com/sorrentum/sorrentum/assets/70459407/62bc134d-49bc-4532-935e-9327e940555f)

Pulled the latest container and merged with master successfully, but now unable to start the docker container with `i docker_bash`.

**Comment by thejameszhang** [comment] 2023-05-26 18:57
![image](https://github.com/sorrentum/sorrentum/assets/70459407/a803b0a6-4dbd-43c6-88d8-6dbd68390f39)

**Comment by samarth9008** [comment] 2023-05-27 10:56
Can you switch to root user and then try to build the thin environment and run the docker commands? Lets see if the problem is related to your ubuntu VM or something else.

**Comment by thejameszhang** [comment] 2023-05-27 23:54
![image](https://github.com/sorrentum/sorrentum/assets/70459407/0e711826-499b-4124-9cee-02440bc4b609)

Got the same KeyError as before.

**Comment by samarth9008** [comment] 2023-05-27 23:57
Your thin environment is not active. 

https://github.com/sorrentum/sorrentum/issues/45#issuecomment-1564359345

**Comment by thejameszhang** [comment] 2023-05-28 00:01
![image](https://github.com/sorrentum/sorrentum/assets/70459407/24fc5391-bc6e-47b8-9bf0-25a7050d48dc)

There seems to be an error building it.

**Comment by PomazkinG** [comment] 2023-05-29 16:29
@thejameszhang so everything is good now?

**Comment by okritvik** [comment] 2023-05-29 17:44
Encountered a fatal error while running `i docker_jupyter`
![Screenshot from 2023-05-29 12-41-50](https://github.com/sorrentum/sorrentum/assets/40200916/54347b94-0a41-4c24-b7ad-b223fd1d7af0)

**Comment by PomazkinG** [comment] 2023-05-29 17:48
> Encountered a fatal error while running i docker_jupyter

simply rename `sorrentum` -> `sorrentum1`. by convention a repo name should name with a digit, this is useful when having multiple clones of a repo

**Comment by okritvik** [comment] 2023-05-29 17:52
> > Encountered a fatal error while running i docker_jupyter
> 
> simply rename `sorrentum` -> `sorrentum1`. by convention a repo name should end with a digit, this is useful when having multiple clones of a repo

Worked. Thanks!

**Comment by thejameszhang** [comment] 2023-05-31 22:25
@okritvik you were able to run all commands without switching to root user?

**Comment by okritvik** [comment] 2023-05-31 23:02
@thejameszhang Yes, I was able to run without switching to root. I guess I added my user itself to the sudoers group. You can either google search depending on your ubuntu version or follow this link https://linuxize.com/post/how-to-add-user-to-sudoers-in-ubuntu/

**Comment by thejameszhang** [comment] 2023-06-01 04:13
![image](https://github.com/sorrentum/sorrentum/assets/70459407/916a23c2-2782-42e6-9428-e68f90cb39fa)

Don't have permission to access the daemon socket when running `invoke docker_bash`, but i was able to pull the latest image and merge with master.

**Comment by PomazkinG** [comment] 2023-06-01 12:43
@thejameszhang you may find [this discussion](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo) helpful. the problem is that when you run `docker pull ...` manually you add the `sudo` prefix and all works, but when running `i docker_bash` it also pulls the image but without the `sudo` prefix.

Try creating a docker group and adding your user to it (see the link above)

**Comment by thejameszhang** [comment] 2023-06-01 21:55
Thanks @PomazkinG I believe that worked. Now I can pull the latest image without sudo. 

![image](https://github.com/sorrentum/sorrentum/assets/70459407/45691495-55d7-4d9d-8669-fd81d9dc88a5)

Did `i docker_bash` run successfully in the below screenshot?

![image](https://github.com/sorrentum/sorrentum/assets/70459407/545837ff-056e-4d45-bc51-3d31554e289c)

**Comment by samarth9008** [comment] 2023-09-07 16:50
Not required anymore. So closing.

**Closed by samarth9008** 2023-09-07 16:50 UTC
